### ISSUE TITLE
Surefire tests not working with maven 3.0.3 - 3.0.4

### ISSUE THREAD

**Issue by gslowikowski** [play1-maven-plugin/play1-maven-plugin#19]
Originally reported on Google Code with ID 19

```
I started a build using a modified version (To match my project requirements) of pom.xml
from "Play! Framework Maven Test Projects : Packagings : WAR : Using Assembly : No
Dependencies"

During the test phase the build stops with this exception...

org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException;
nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:188)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:166)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:101)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/util/DirectoryScanner
        at com.google.code.play.surefire.junit4.PlayDirectoryScanner.collectTests(PlayDirectoryScanner.java:114)
        at com.google.code.play.surefire.junit4.PlayDirectoryScanner.locateTestClasses(PlayDirectoryScanner.java:71)
        at com.google.code.play.surefire.junit4.PlayJUnit4Provider.scanClassPath(PlayJUnit4Provider.java:284)
        at com.google.code.play.surefire.junit4.PlayJUnit4Provider.invoke(PlayJUnit4Provider.java:175)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.util.DirectoryScanner
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
        at org.apache.maven.surefire.booter.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:93)
        ... 13 more


Im using maven-play-plugin 1.0.0-alpha6 with maven 3.0.3. I also tried maven 3.0.4
with similar results 

I found a work around to the problem. I added a dependency to org.codehaus.plexus.util
with a scope of test in my project pom

<dependency>
    <groupId>org.codehaus.plexus</groupId>
    <artifactId>plexus-utils</artifactId>
    <version>3.0</version>
    <scope>test</scope>
</dependency>

This seems to work for me.
I just wanted to let you know about the work around.

Thanks for the great work!
-Alain

```

Reported by `alain.laniel@marexa.ca` on 2012-01-24 16:04:39
